data_load:
  path_to_dataframe: /home/storage/projects/sber_project_priceseekers/data/rosbank/rosbank_features.parquet 
  #name of the column with the target variable 
  target_col: target
data_save:
  #user defined name of the dataset
  data_name: rosbank
  #path to a directory where embeddings and targets will be saved
  path_to_save: /home/storage/projects/sber_project_priceseekers/data/rosbank
pca:
  #standardize features before apply the PCA method
  is_standard_scaler: True
  #the estimated number of components. 
  n_components: 0.95

